### ISSUE TITLE
Option to reset killstreak after reaching end.

### ISSUE THREAD

**Issue by mibby** [confuser/Bukkit-KillStreaks#3]
Would it be possible to add an option to reset the killstreak rewards after you have reached the end? For example, go back to 1 after reaching the maximum of 10?

Alternatively, would it be possible to have a reward for every kill in addition to the killstreak rewards so you can still get a reward when your streak is maxed out?

**Comment by confuser** [comment]
Yes, possible by using the `/ksreset <player>` command as the reward for the last kill streak. It'll reset their streaks and set them back to 0.

Alternative should also be possible as well, by defining a `level` reward.
